spring:
  application:
    name: saga-member-service

  datasource:
    url: jdbc:mysql://localhost:3306/liveshop
    username: liveshop
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver

    # flyway DDL을 맡기므로 JPA는 DDL 관여하지 않고, 유효성 검증만 하자
    jpa:
      hibernate:
        ddl-auto: validate


    flyway:
      enabled: true
      # 기존에 테이블이 있어도 무시하고 Flyway 이력을 기록하기 시작함
      baseline-on-migrate: true
      # 마이그레이션 파일이 없을 때의 기준 버전 (보통 0)
      baseline-version: 0

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.flywaydb: info

