spring:
  application:
    name: saga-member-service

  datasource:
    url: jdbc:mysql://localhost:3306/liveshop
    username: liveshop
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver

    # flyway DDL을 맡기므로 JPA는 DDL 관여하지 않고, 유효성 검증만 하자
    jpa:
      hibernate:
        ddl-auto: validate

    flyway:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.flywaydb: info

