spring:
  application:
    name: saga-member-service

  #CI 테스트에서는 Config Server의 존재를 없애 버려야 하므로
  config:
    import: "optional:none"

  cloud:
    config:
      enabled: false
      fail-fast: false